language: node_js
node_js:
  - "12"
branches:
  only:
    - angularjs
cache:
  directories:
     - ./node_modules
install:
  - cd example
  - npm install
script:
  - npm run build
  - cd dist && cp index.html 404.html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: example/dist
  on:
    branch: angularjs
